Feature/home screen
MuresanCoralia/HungryWolfs pull request #4
Opened 2021-08-17 12:32 UTC by MuresanCoralia

2021-08-19 07:37 UTC, paultiriteuWP requested changes
There are just a few comments, but good job on this PR 👍

2021-08-19 07:37 UTC, paultiriteuWP commented on CategoryCollectionViewCell.swift
> +{
Braces should be on the same line with the class declaration

2021-08-19 07:37 UTC, paultiriteuWP commented on CategoryCollectionViewCell.swift
> +    {
Same for the functions

2021-08-19 07:37 UTC, paultiriteuWP commented on Food.swift
> +    var strCategoryDescription: String
Can we change these fields to id, name, thumb and description? Ask Vlad for help as he already done this

2021-08-19 07:37 UTC, paultiriteuWP commented on HomeScreenViewController.swift
> +       // tabBar.clipsToBounds = true
Do we need this line?

2021-08-19 07:37 UTC, paultiriteuWP commented on HomeScreenViewController.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CategoryCollectionViewCell", for: indexPath) as! CategoryCollectionViewCell
We should avoid force unwrapping as much as possible. Here we can do `guard let cell ... as? CategoryCollectionViewCell else { return UITableViewCell() }`

2021-08-19 07:37 UTC, paultiriteuWP commented on HomeScreenViewController.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MealsCollectionViewCell", for: indexPath) as! MealsCollectionViewCell
Same here

2021-08-19 07:37 UTC, paultiriteuWP commented on HomeScreenViewController.swift
> +            let cell = collectionView.cellForItem(at: indexPath) as? CategoryCollectionViewCell
Do we use this cell?

2021-08-19 07:37 UTC, paultiriteuWP commented on Meals.swift
> +    var idMeal: String
Same here, can we change the names of these fields?

2021-08-19 07:37 UTC, paultiriteuWP commented on ViewController.swift
> +
Do we need this file?

2021-08-20 11:09 UTC, dan-ilies-wd requested changes

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/DetailsMeal/DetailViewController.swift
> +                self?.mealTag1Label.text = tagList?[0]
You can create separate functions that configure each tagView, and just call them from there (like: self.configureTagView1, self.configureTagView2).

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/DetailsMeal/DetailViewController.swift
> +        // de luat datele
Let's remove the unused code and empty spaces :D

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/Favourites/FavouriteTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Let's remove this function if it only calls super.

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/HomeScreen/HomeScreenViewController.swift
> +    override func viewWillAppear(_ animated: Bool)
ViewWillAppear can be at the top of the class, under ViewDidLoad.

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/HomeScreen/HomeScreenViewController.swift
> +
Let's remove some of these empty lines.

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/Model/Details.swift
> +        case id = "idMeal"
Nice 👏

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/Profile/ProfileViewController.swift
> +        if let url = NSURL(string: "https://www.wolfpack-digital.com/privacy") {
You can use URL instead of NSURL.

2021-08-20 11:09 UTC, dan-ilies-wd commented on HungryWolfs/Search/SearchViewController.swift
> +                self?.foundLabel.text = "Found \(nrOfResults) result"
Good catch here 👍

2021-08-24 07:58 UTC, closed without merging